# Backbone
backbone: resnet50

# Transfer related
transfer_loss_weight: 1.0
transfer_loss: coral

# Metric related
metric: arc_margin   # arc_margin/add_margin/sphere
metric_s: 20
metric_m: 0.5
metric_loss_weight: 0.5

# Entropy related
entropy_loss_weight: 0.05

# Optimizer related
lr: 0.01
weight_decay: 0.001
lr_scheduler: True
lr_gamma: 10
lr_decay: 0.75
momentum: 0.9

# Training related
n_iter_per_epoch: 100
n_epoch: 20

# Others
seed: 1
num_workers: 3
