# Backbone
backbone: resnet50

# Transfer related
transfer_loss_weight: 0.5
transfer_loss: lmmd

# Metric related
metric: arc_margin   # arc_margin/add_margin/sphere
metric_s: 8
metric_m: 0.5
metric_loss_weight: 0.1

# Entropy related
entropy_loss_weight: 0.0005

# Optimizer related
lr: 0.01
weight_decay: 5e-4
momentum: 0.9
lr_scheduler: True
lr_gamma: 0.0003
lr_decay: 0.75

# Training related
n_iter_per_epoch: 100
n_epoch: 20

# Others
seed: 1
num_workers: 3
